    services:
      db:
        build:
          context: ./postgresql
        ports:
          - "5433:5432"  # Изменил порт с 5432 на 5433
        environment:
          POSTGRES_USER: boltenkov
          POSTGRES_PASSWORD: password
          POSTGRES_DB: boltenkov_db
        volumes:
          - db_data:/var/lib/postgresql/data
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U boltenkov -d boltenkov_db"]
          interval: 10s
          timeout: 5s
          retries: 5

      app:
        build:
          context: ./app
        depends_on:
          db:
            condition: service_healthy
        environment:
          DB_HOST: db
          DB_NAME: boltenkov_db
          DB_USER: boltenkov
          DB_PASSWORD: password
        volumes:
          - ./app:/app
        command: python /app/main.py

    volumes:
      db_data:
    

